Feat: materi 3 chapter 2 (css grid layout)
surabayadev/tutorial-css-lengkap pull request #17
Opened 2024-10-23 10:48 UTC by yudistiraashadi

Pull request untuk #10 tutorial css grid layout

2024-10-24 08:17 UTC, iniakunhuda requested changes
Ada beberapa feedback yang perlu diperbaiki sedikit lagi mas

- Materi "Properti Display Grid" di tantangan numberingnya start mulai dari 1
- Materi "Properti Display Grid" dan "Contoh layout dengan Grid dan Flexbox" tolong tambahkan image (result) di bawah tantangan agar user kebayang bagaimana expected result yang harus dibuat

Taruh file di folder _assets, bisa melihat caranya [disini](https://github.com/surabayadev/tutorial-css-lengkap/pull/16/commits/37b237720bccffe4972d3ab57213cb0643784b93)

2024-10-25 03:19 UTC, yudistiraashadi commented
> Ada beberapa feedback yang perlu diperbaiki sedikit lagi mas
> 
> * Materi "Properti Display Grid" di tantangan numberingnya start mulai dari 1
> * Materi "Properti Display Grid" dan "Contoh layout dengan Grid dan Flexbox" tolong tambahkan image (result) di bawah tantangan agar user kebayang bagaimana expected result yang harus dibuat
> 
> Taruh file di folder _assets, bisa melihat caranya [disini](https://github.com/surabayadev/tutorial-css-lengkap/pull/16/commits/37b237720bccffe4972d3ab57213cb0643784b93)

Okay mas Huda

2024-10-25 08:16 UTC, iniakunhuda commented
LGTM

2024-10-25 08:20 UTC, iniakunhuda commented
Overall content is great, please next time pull request to branch staging ya mas @yudistiraashadi. Thank you!

2024-10-25 08:20 UTC, merged