feat: add materi flexbox
surabayadev/tutorial-css-lengkap pull request #18
Opened 2024-10-25 07:56 UTC by DimasZeava

- menambahkan materi pengantar flexbox beserta tantangannya
- menambahkan materi properti flexbox beserta tantangannya
- menambahkan contoh penerapan flexbox beserta tantangannya
- siap melakukan revisi materi apabila materi dirasa kurang

2024-10-25 07:57 UTC, DimasZeava commented
Izin tag mas huda @iniakunhuda untuk pull request

2024-10-25 16:21 UTC, iniakunhuda requested changes
Materinya sudah bagus. Ada beberapa feedback yang perlu diperbaiki sedikit lagi mas

- Tiap materi tolong tambahkan image (result) di bawah tantangan agar user kebayang bagaimana expected result yang harus dibuat

Taruh file gambar di folder _assets, bisa melihat caranya [disini](https://github.com/surabayadev/tutorial-css-lengkap/pull/16/commits/37b237720bccffe4972d3ab57213cb0643784b93)

2024-10-25 16:23 UTC, iniakunhuda commented
@DimasZeava tlg update lagi yaa

2024-10-25 19:48 UTC, DimasZeava commented
Siap mas huda

2024-10-27 02:20 UTC, DimasZeava commented
kira kira dari perbaikan yang sudah dilakukan, apakah sudah cukup atau masih diperlukan perubahan lagi mas huda?

2024-10-27 03:44 UTC, iniakunhuda commented
LGTM

2024-10-27 03:44 UTC, merged

2024-10-27 03:45 UTC, iniakunhuda commented
It has been merged, please check hacktoberfest website yah @DimasZeava